```yaml
version: 2

models:
  - name: your_model_name_here                   # replace with actual model name
    description: |
      Incremental model summarizing user activity for the last 30 days.
      This model combines user profiles with recent activities to provide key metrics such as total activities per user 
      and their most recent activity date. It is optimized for performance with incremental updates, partition pruning, 
      and efficient window functions. Useful for tracking active users and engagement trends in recent periods.
    meta:
      owner: "analytics_team"
      domain: "user_engagement"
      source: 
        - name: user_activity_raw
          description: "Raw source table containing user activity events including types and dates"
        - name: user_profiles
          description: "Source dimension table with user profile information such as name and signup date"
    columns:
      - name: user_id
        description: |
          Unique identifier for each user. This serves as the primary key for the model and is used as the unique key 
          for incremental merging.
        data_type: integer
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('user_profiles')
              field: user_id
          - relationships:
              to: source('user_activity_raw', 'user_id')
              field: user_id

      - name: user_name
        description: |
          The full name of the user, sourced from the user_profiles table. Represents the registered name associated 
          with the user account.
        data_type: varchar(100)
        tests:
          - not_null

      - name: signup_date
        description: |
          The date when the user signed up or created their account. This field allows analysis of user tenure and 
          cohort segmentation.
        data_type: date
        tests:
          - not_null
          - dbt_utils.date_not_future:
              column_name: signup_date

      - name: total_activities
        description: |
          The total count of user activities in the last 30 days, aggregated across all activity types. This metric 
          captures user engagement volume.
        data_type: integer
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "total_activities >= 0"
        meta:
          examples:
            - "total_activities = 0 indicates a user with no recorded activities in the last 30 days"
            - "Higher values reflect more frequent user engagement"

      - name: last_activity_date
        description: |
          The date of the most recent activity performed by the user within the last 30 days. It is null if the user 
          has no recorded activities in this period.
        data_type: date
        tests:
          - dbt_utils.expression_is_true:
              expression: "last_activity_date <= current_date"
          - dbt_utils.expression_is_true:
              expression: "last_activity_date IS NULL OR last_activity_date >= dateadd(day, -30, current_date)"
```